<h1 style="text-align: center;"><strong>Machine Learning & Data Science</strong></h1>
<h2 style="text-align: center;"><strong>Analise Exploratória I - Conhecendo os dados</strong></h2>
<h3 style="text-align: center;"><strong>Eduardo Ferreira</strong></h3>
<h4 style="text-align: center;"><strong>eduds1010@gmail.com</strong></h4>
<h5 style="text-align: center;"><strong>https://github.com/blequizit</strong></h5>
<br>
<p style="text-align: center;"><em>Este projeto aplica técnicas de análise exploratória de dados para investigar os fatores que influenciam o preço de carros.</em></p>
<br>

# **Dicionário de dados**

Car_ID			:	Unique id of each observation (Interger)

Symboling 			:	Its assigned insurance risk rating, A value of +3 indicates that the auto is risky, -3 that it is probably
pretty safe.(Categorical)

carCompany			:	Name of car company (Categorical)

fueltype			:	Car fuel type i.e gas or diesel (Categorical)

aspiration			:	Aspiration used in a car (Categorical)

doornumber			:	Number of doors in a car (Categorical)

carbody			:	body of car (Categorical)

drivewheel			:	type of drive wheel (Categorical)

enginelocation			:	Location of car engine (Categorical)

wheelbase			:	Weelbase of car (Numeric)

carlength			:	Length of car (Numeric)

carwidth			:	Width of car (Numeric)

carheight			:	height of car (Numeric)

curbweight			:	The weight of a car without occupants or baggage. (Numeric)

enginetype			:	Type of engine. (Categorical)

cylindernumber			:	cylinder placed in the car (Categorical)

enginesize			:	Size of car (Numeric)

fuelsystem			:	Fuel system of car (Categorical)

boreratio			:	Boreratio of car (Numeric)

stroke			:	Stroke or volume inside the engine (Numeric)

compressionratio			:	compression ratio of car (Numeric)

horsepower			:	Horsepower (Numeric)

peakrpm			:	car peak rpm (Numeric)

citympg			:	Mileage in city (Numeric)

highwaympg			:	Mileage on highway (Numeric)

price(Dependent variable)			:	Price of car (Numeric)

## Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib

In [ ]:
pd.set_option('display.max_columns', 100) # Altera a quantidade de colunas apresentada do dataset

## Leitura do dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Machine Learning & Data Science/Dados/CarPrice_Assignment.csv")

## Análise Exploratória

In [ ]:
df.sample(5)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
32,33,1,honda civic,gas,std,two,hatchback,fwd,front,93.7,150.0,64.0,52.6,1837,ohc,four,79,1bbl,2.91,3.07,10.1,60,5500,38,42,5399.0
51,52,1,maxda glc deluxe,gas,std,two,hatchback,fwd,front,93.1,159.1,64.2,54.1,1900,ohc,four,91,2bbl,3.03,3.15,9.0,68,5000,31,38,6095.0
68,69,-1,buick century luxus (sw),diesel,turbo,four,wagon,rwd,front,110.0,190.9,70.3,58.7,3750,ohc,five,183,idi,3.58,3.64,21.5,123,4350,22,25,28248.0
41,42,0,honda civic,gas,std,four,sedan,fwd,front,96.5,175.4,65.2,54.1,2465,ohc,four,110,mpfi,3.15,3.58,9.0,101,5800,24,28,12945.0
160,161,0,toyota corona,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,53.0,2094,ohc,four,98,2bbl,3.19,3.03,9.0,70,4800,38,47,7738.0

In [ ]:
df.describe() # describe apresenta estatísticas sobre as variáveis numéricas

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [ ]:
df.describe(include='object') # describe apresenta estatísticas sobre as variáveis categóricas

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,enginetype,cylindernumber,fuelsystem
count,205,205,205,205,205,205,205,205,205,205
unique,147,2,2,2,5,3,2,7,7,8
top,toyota corona,gas,std,four,sedan,fwd,front,ohc,four,mpfi
freq,6,185,168,115,96,120,202,148,159,94

In [ ]:
df.isnull().sum() / len(df) # Lista variáveis com dados faltantes

car_ID              0.0
symboling           0.0
CarName             0.0
fueltype            0.0
aspiration          0.0
doornumber          0.0
carbody             0.0
drivewheel          0.0
enginelocation      0.0
wheelbase           0.0
carlength           0.0
carwidth            0.0
carheight           0.0
curbweight          0.0
enginetype          0.0
cylindernumber      0.0
enginesize          0.0
fuelsystem          0.0
boreratio           0.0
stroke              0.0
compressionratio    0.0
horsepower          0.0
peakrpm             0.0
citympg             0.0
highwaympg          0.0
price               0.0
dtype: float64

In [ ]:
print(f"Número de linhas duplicadas: {df.duplicated().sum()}")

Número de linhas duplicadas: 0

## Exploração Grafica

#### Distribuição da variável alvo (Price)

In [ ]:
fig = px.histogram(df, x='price', nbins=30, title='Distribuição dos preços dos carros', color_discrete_sequence=['blue'])
fig.show()

##### Distribuição das variáveis categóricas

In [ ]:
cat_cols = df.select_dtypes(include='object') # Separa somente as colunas com data type object

for col in cat_cols:
    fig = px.histogram(df, x=col, title=f'Distribuição das {col}', color_discrete_sequence=['purple'])
    fig.show()

#### Correlação entre variáveis numéricas

In [ ]:
df_num = df.select_dtypes(exclude='object') # Gera dataset com apenas variáveis numericas
correlation = df_num.corr() # gera matriz de correlação
fig = px.imshow(correlation,title='Mapa de calor das correlações do dataset de vendas de carros')
fig.show()

##### Exploração Price

In [ ]:
fig = px.scatter(df, x="enginesize", y="price", trendline="ols",
                 title="Relação entre o tamanho do motor e o preço do carro")
fig.show()

In [ ]:
fig = px.box(df, x="carbody", y="price", color="carbody", title="Distribuição de preços por tipo de carroceria")
fig.show()

In [ ]:
fig = px.box(df, x="fueltype", y="price", color="fueltype", title="Distribuição de preços por tipo de combustivel")
fig.show()

In [ ]:
fig = px.scatter(df, x="curbweight", y="price", trendline="ols",
                 title="Relação entre o peso do carro e o preço do carro")
fig.show()

In [ ]:
# Valor médio de venda dos carros por tipo de combustivel
fig = px.bar(df.groupby("fueltype")["price"].mean().reset_index(), x="fueltype", y="price",
              title="Valor médio de venda dos carros por tipo de combustível", color_discrete_sequence=["orange"])
fig.show()

In [ ]:
fig = px.box(df, x="aspiration", y="price", color="aspiration", title="Distribuição de preços por tipo aspiração do motor")
fig.show()

In [ ]:
# Valor médio de venda dos carros por tipo de combustivel
fig = px.bar(df.groupby("aspiration")["price"].mean().reset_index(), x="aspiration", y="price",
              title="Valor médio de venda dos carros por tipo de Aspiração", color_discrete_sequence=["orange"])
fig.show()

In [ ]:
fig = px.box(df, x="drivewheel", y="price", color="drivewheel", title="Distribuição de preços por tipo de tração")
fig.show()

In [ ]:
fig = px.box(df, x="cylindernumber", y="price", color="cylindernumber", title="Distribuição de preços por Quantidade de cilindros no motor")
fig.show()

##### Exploração por consumo na cidade

In [ ]:
fig = px.scatter(df, x="enginesize", y="citympg", trendline="ols",
                 title="Relação entre o tamanho do motor e o consumo na cidade")
fig.show()

In [ ]:
fig = px.scatter(df, x="horsepower", y="citympg", trendline="ols",
                 title="Relação entre a potencia do carro e o consumo na cidade")
fig.show()

In [ ]:
fig = px.scatter(df, x="curbweight", y="citympg", trendline="ols",
                 title="Relação entre o peso do carro e o consumo na cidade")
fig.show()

In [ ]:
fig = px.box(df, x="cylindernumber", y="citympg", color="cylindernumber", title="Distribuição de milhas por galão por Quantidade de cilindros no motor")
fig.show()

In [ ]:
fig = px.box(df, x="drivewheel", y="citympg", color="drivewheel", title="Distribuição de milhas por galão por Quantidade tipo de tração")
fig.show()

In [ ]:
df[["compressionratio", "horsepower"]].corr()

                  compressionratio  horsepower
compressionratio          1.000000   -0.204326
horsepower               -0.204326    1.000000